## Default values for kube-downscaler.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

## How many kube-downscaler pods should run in deployment
replicaCount: 1
name: kube-downscaler
debug:
  enable: True

## Namespace where kube-downscaler is going to be deployed.
namespace:
  ## Deployment will query all namespaces if left empty:
#  active_in:
  ## Deployment exclude these namespaces:
  inactive_in:
    - openshift.*
    - cert-manager
    - dr-app-charts
    - harness-delegate
    - ingress-nginx
    - kube.*
    - kyverno
    - namespace-terminator
    - nvidia-gpu-operator
## How frequently kube-downscaler should query applications uptime, unit is in seconds.

## Default is 1 minute.
interval: 10
rbac:
  ## If true, create & use RBAC resources
  create: true
  ## Ignored if rbac.create is true
  serviceAccountName: default
image:
  repository: apolyakov/kube-downscaler
  tag: 23.2.0-1
  pullPolicy: IfNotPresent
  args: [--matching-labels=.*, --auto-downscale, --auto-downscale-period-seconds=10800]
    # --default-uptime="Mon-Fri 07:30-20:30 Europe/Berlin"
resources:
  limits:
    cpu: 50m
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 200Mi

  ## Allow the DaemonSet to schedule on tainted nodes (requires Kubernetes >= 1.6)
  # tolerations: []

  ## Allow the DaemonSet to schedule on selected nodes
  # Ref: https://kubernetes.io/docs/user-guide/node-selection/
  # nodeSelector: {}

  ## Allow the DaemonSet to schedule ussing affinity rules
  # Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  # affinity: {}
