apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: kube-downscaler
    version: v23.2.0
  name: kube-downscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-downscaler
  template:
    metadata:
      labels:
        application: kube-downscaler
        version: v23.2.0
    spec:
      serviceAccountName: kube-downscaler
      containers:
      - name: downscaler
        image: apolyakov/kube-downscaler:23.2.0-1
        imagePullPolicy: Always
        args:
          # dry run by default, remove to perform downscaling
          #- --dry-run
          # run every minute
          - --interval=10
          - --debug
          - --namespace=dr-app
          - --matching-labels=.*
          - --include-resources=deployments,statefulsets,cronjobs
        envFrom:
          - configMapRef:
              name: kube-downscaler
              optional: true
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 5m
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
